version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quizmaker
      - SECRET_KEY=your-secret-key-replace-in-production
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quizmaker
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: 